; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.10"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0-rc1"

projects[ckeditor][subdir] = "sites/all/modules/contrib/ckeditor"
projects[ckeditor][version] = "1.6"

projects[features][subdir] = "sites/all/modules/contrib/features"
projects[features][version] = "1.0-beta6"

projects[fivestar][subdir] = "sites/all/modules/contrib/fivestar"
projects[fivestar][version] = "2.0-alpha1"

projects[galleryformatter][subdir] = "sites/all/modules/contrib/galleryformatter"
projects[galleryformatter][version] = "1.0"

projects[jcarousel][subdir] = "sites/all/modules/contrib/jcarousel"
projects[jcarousel][version] = "2.6"

projects[libraries][subdir] = "sites/all/modules/contrib/libraries"
projects[libraries][version] = "1.0"

projects[lightbox2][subdir] = "sites/all/modules/contrib/lightbox2"
projects[lightbox2][version] = "1.0-beta1"

projects[omega_tools][subdir] = "sites/all/modules/contrib/omega_tools"
projects[omega_tools][version] = "3.0-rc3"

projects[sharethis][subdir] = "sites/all/modules/contrib/sharethis"
projects[sharethis][version] = "2.2"

projects[views][subdir] = "sites/all/modules/contrib/views"
projects[views][version] = "3.0"

projects[views_slideshow][subdir] = "sites/all/modules/contrib/views_slideshow"
projects[views_slideshow][version] = "3.0"

projects[votingapi][subdir] = "sites/all/modules/contrib/votingapi"
projects[votingapi][version] = "2.4"

; Themes
projects[omega][version] = "3.0"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[drewpull_theme][download][type] = "git"
projects[drewpull_theme][download][url] = "git@github.com:rteijeiro/drewpull-theme.git"
projects[drewpull_theme][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "https://raw.github.com/malsup/cycle/master/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

libraries[ckeditor][download][type]= "get"
libraries[ckeditor][download][file_type] = "tar.gz"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "modules/contrib/ckeditor"
libraries[ckeditor][overwrite] = TRUE

